apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: noizy23yo/hero_devops:tm-frontend
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_BACKEND_URL
              value: "30001"
