apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9rdXNoYWxyYW8xMDM6ZVpnTEFSUjFwMnhTR2ZHVUBjbHVzdGVyMC4xYTNpcS5tb25nb2RiLm5ldC9UcmF2ZWxNZW1vcnk=
